version: '3.8'

services:
  backend:
    container_name: backend
    expose:
      - 8000
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    command:
      uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
#    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw